# Generated by Django 5.1.4 on 2024-12-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0005_alter_booking_seats_alter_booking_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='Run',
        ),
        migrations.AlterModelTable(
            name='run',
            table='bus',
        ),
    ]
